### ISSUE TITLE
Nix package: env: node\r: No such file or directory

### ISSUE THREAD

**Issue by rfaulhaber** [emacs-eask/cli#106]
When I install or run the eask CLI using Nix, such as:

```
nix run nixpkgs#nodePackages.eask
```

I receive the error:

```
env: node\r: No such file or directory
```

My current workaround is to alias eask to `node $(which eask)`, which seems to work. I guess the file it installs is using CRLF endings?

**Comment by jcs090218** [comment]
Ah, yes. I developed on Windows so the line endings is CRLF...

**Comment by jcs090218** [comment]
I have published a new version for this Can you try reinstall and upgrade to `0.7.8`?

Should fix in 22996690bc5e3f1d134126fdaad8f0e23b346742.

#### Some refs:

- https://github.com/npm/npm/issues/12371
- https://github.com/enlight/electron-inspector/issues/1
- https://github.com/http-party/http-server/issues/420

**Comment by rfaulhaber** [comment]
Well I can't speak to the Nix package specifically, however I pulled out my macbook and installed eask@0.7.7 globally using yarn (I read somewhere that yarn doesn't handle line endings but npm does, which I suspect is why this might not have been an issue for most people) and I could reproduce the issue. I then upgraded to 0.7.8 and eask runs fine! I'd imagine this would resolve the issue when the latest version becomes available on nixpkgs.

**Comment by jcs090218** [comment]
Just a note here, there are multiple ways to install Eask, see [Install Eask](https://emacs-eask.github.io/Getting-Started/Install-Eask/) from our page.

* The most simplest way is through [npm](https://emacs-eask.github.io/Getting-Started/Install-Eask/#npm) since you don't need to worry about the PATH environment
* Best for development is through [source](https://emacs-eask.github.io/Getting-Started/Install-Eask/#-source). (Looking to use latest features)
* Looking for stablest, is through [binary](https://emacs-eask.github.io/Getting-Started/Install-Eask/#binary-cross-platform) (Recommended for most users)
