### ISSUE TITLE
symbolic link to eask executable is not working

### ISSUE THREAD

**Issue by conao3** [emacs-eask/cli#125]
Hi, I usually build something softwares in `~/.local/work/xxx` and `ln` from `~/.local/bin/`.
This workflow is works well but eask executable occur error.

```
cd ~/.local/work
git clone https://github.com/emacs-eask/cli eask
cd eask
npm install
cd ~/.local/bin
ln -s ../work/eask/bin/eask
eask
```

will shows below error.
```
$ eask
node:internal/modules/cjs/loader:1063
  throw err;
  ^

Error: Cannot find module '/home/conao/.local/eask'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1060:15)
    at Module._load (node:internal/modules/cjs/loader:905:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.6.0
```

I think the executable should work regardless of the current directory. How about it?

**Comment by jcs090218** [comment]
The issue came from unresolved symbolic link path:

https://github.com/emacs-eask/cli/blob/00e2646c5933dbe46e4474dec1b232820d0e8ca8/bin/eask#L20-L21

I think `@Fuco1` is trying to resolve this issue in #24. Sorry, I am not a bash expert, so I don't know how to resolve symbolic link issues both in Linux and macOS at the same time. 😓 But I would definitely like to resolve this issue.

**Comment by jcs090218** [comment]
Ah, I think I've found the solution, it should be resolved in #126.

**Comment by conao3** [comment]
wow! Thanks, the issue I mentioned is solved!

**Comment by conao3** [comment]
BTW, eask looks very good to me and I will use it!

**Comment by jcs090218** [comment]
Awesome! I've spent so much time on this! Thank you for using it! ❤️ 🚀 😁
